version: 7
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy: []
  paste:
    - - Ctrl
      - ⌘-V
    - - Ctrl
      - ⌘-V
  home:
    - - ⌘-Left
  end:
    - - ⌘-Right
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-next-word:
    - ⌥-Delete
  clear:
    - ⌘-K
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  ctrl-c:
    - - Ctrl
      - ⌘-C
  copy-current-path: []
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - - ⌘-N
  new-tab:
    - - ⌘-T
    - - Ctrl-N
  profile-selector:
    - ⌘-E
  toggle-fullscreen:
    - Ctrl+⌘+F
  rename-tab:
    - ⌘-R
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - ⌘-Shift
  duplicate-tab: []
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10:
    - ⌘-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-maximize:
    - ⌘-⌥-Enter
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  switch-profile:
    - ⌘-Shift-E
  close-pane:
    - ⌘-Shift-W
  profile: {}
  profile-selectors: {}
  select-all:
    - ⌘-A
  scroll-to-bottom: []
  settings-tab: {}
  explode-tab:
    - ⌘-Shift-.
  combine-tabs:
    - ⌘-Shift-,
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  delete-line:
    - ⌘-Backspace
  focus-all-tabs:
    - ⌘-⌥-Shift-I
  scroll-to-top:
    - Shift-PageUp
  scroll-up:
    - ⌥-PageUp
  scroll-down:
    - ⌥-PageDown
  restart-tab: []
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  command-selector:
    - ⌘-Shift-P
  reconnect-tab: []
  disconnect-tab: []
terminal:
  searchOptions: {}
  colorScheme:
    name: 3024 Night
    foreground: '#a5a2a2'
    background: '#090300'
    cursor: '#a5a2a2'
    colors:
      - '#090300'
      - '#db2d20'
      - '#01a252'
      - '#fded02'
      - '#01a0e4'
      - '#a16a94'
      - '#b5e4f4'
      - '#a5a2a2'
      - '#5c5855'
      - '#e8bbd0'
      - '#3a3432'
      - '#4a4543'
      - '#807d7c'
      - '#d6d5d4'
      - '#cdab53'
      - '#f7f7f7'
  customColorSchemes: []
  copyOnSelect: true
  profile: local:custom:Fish:191ef8bd-5380-45a0-ad56-5e435ff33780
  ligatures: true
  altIsMeta: true
  background: colorScheme
  fontSize: 17
ssh: {}
configSync:
  parts: {}
clickableLinks: {}
appearance:
  opacity: 0.97
  frame: native
hacks: {}
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  local:
    type: local
    options:
      env: {}
      command: /bin/fish
      args: []
  ssh:
    type: ssh
    options:
      algorithms: {}
    terminalColorScheme:
      name: 3024 Day
      foreground: '#4a4543'
      background: '#f7f7f7'
      cursor: '#4a4543'
      colors:
        - '#090300'
        - '#db2d20'
        - '#01a252'
        - '#fded02'
        - '#01a0e4'
        - '#a16a94'
        - '#b5e4f4'
        - '#a5a2a2'
        - '#5c5855'
        - '#e8bbd0'
        - '#3a3432'
        - '#4a4543'
        - '#807d7c'
        - '#d6d5d4'
        - '#cdab53'
        - '#f7f7f7'
profiles:
  - name: Zsh
    options:
      env:
        PATH: /usr/local/bin:$PATH
      cwd: /Users/arachanoian
      command: /bin/zsh
      args: []
    id: local:custom:Fish:191ef8bd-5380-45a0-ad56-5e435ff33780
    disableDynamicTitle: true
    type: local
accessibility: {}
groups: []
providerBlacklist: []
commandBlacklist: []
profileBlacklist: []
enableAnalytics: false
